services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        networks:
            - laravel

    nginx:
        image: nginx:stable-alpine
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        depends_on:
            - php
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel-docker-demo
            MYSQL_USER: docker
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
