version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_php
        volumes:
            - .:/var/www/html:cached # Mejor rendimiento para macOS/Windows
            - ./php.ini:/usr/local/etc/php/php.ini # Configuración personalizada de PHP
        environment:
            PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1 # Asegura que los cambios se reflejen de inmediato
        networks:
            - laravel
        depends_on:
            - mysql

    nginx:
        image: nginx:stable-alpine
        container_name: laravel_nginx
        volumes:
            - .:/var/www/html:cached
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        depends_on:
            - php
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel-docker-demo
            MYSQL_USER: docker
            MYSQL_PASSWORD: secret
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # Opcional: evita problemas en desarrollo local
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql # Persistencia de datos
        networks:
            - laravel

volumes:
    mysql-data:
        driver: local # Persistencia para la base de datos

networks:
    laravel:
        driver: bridge
